wandb_version: 1

Factor:
  desc: null
  value: 0.75
Init:
  desc: null
  value: zero
Threshold:
  desc: null
  value: 3
Window:
  desc: null
  value: 4
_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1679873569.892587
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.8.5
      5: 0.14.0
      8:
      - 1
      - 3
      - 5
