wandb_version: 1

Factor:
  desc: null
  value: 1
Window:
  desc: null
  value: 3
_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1680034590.223824
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.8.5
      5: 0.14.0
      8:
      - 1
      - 3
      - 5
