wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1680033156.807165
    t:
      1:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.8.5
      5: 0.14.0
      8:
      - 1
      - 3
      - 5
