wandb_version: 1

Factor:
  desc: null
  value: 1.0e-06
Init:
  desc: null
  value: relu
Threshold:
  desc: null
  value: 1.5
Window:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1678926863.096765
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.8.5
      5: 0.14.0
      8:
      - 1
      - 3
      - 5
